### ISSUE TITLE
Page scraping code should not be defined in the Job class 

### ISSUE THREAD

**Issue by olivierobert** [nhutle/laravel-crawler-app#3]
`CrawlerJob` currently has 2 responsibilities:
- Running a job as part of implementing `ShouldQueue`
- Crawling the Google result page

As the single responsibility principle goes, each object have clearly defined role. Here executing the job should be the main responsibility. The actual page scraping should be done by another object or module entirely. A major benefit would be testability of the page scraping without running the job for instance.

**Comment by nhutle** [comment]
Yes, I've just separated it into GoogleSerp class. Thanks for the suggestion.
