### ISSUE TITLE
Each keyword should have a separate page scraping job

### ISSUE THREAD

**Issue by olivierobert** [nhutle/laravel-crawler-app#4]
`CrawlerJob` currently loops through a list of keywords. But a better approach would be for each job to perform the page scraping for one single word. 

With the current implementation, what would happen if an exception is raised for any of the keywords of the list? Would the page scraping for the yet-to-be-scraped keyword fail too?

**Comment by nhutle** [comment]
Yeah, you are right, it's better to separate them into small jobs.
Thank you for the hint.
