### ISSUE TITLE
Do not leave commented code behind

### ISSUE THREAD

**Issue by olivierobert** [nhutle/laravel-crawler-app#7]
![image](https://user-images.githubusercontent.com/696529/79835098-57f3ee00-83d8-11ea-8279-3b702070319d.png)

In the most critical part of the codebase, it appears that there is a lot of commented code left behind. Make sure to remove all un-necessary code before committing and/or merging.

**Comment by nhutle** [comment]
Yes, sorry I was trying to crawl with possible options but none of them return "Ad num" of a keyword. It look likes Google doesn't allow us to crawl its pages within simple curl set up. I'm working on it now to remove them.
